apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: red-pod
  name: red-pod
spec:
  containers:
  - env:
    - name: APP_COLOR
      value: red
    image: mmumshad/simple-webapp-color
    name: red-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
